name: Publish
on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/langchain-asyncpg
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build
        run: uv build
      - name: Publish to pypi
        run: uv publish --index simple --token ${{ secrets.PYPI_API_TOKEN }}